config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'

	resources :restaurants do 
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :reviews, dependent: :destroy
	validates :name, :address, :phone_number, presence: true
	validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :fetch_restaurant, only: [:show, :edit, :update, :destroy]

	def index
		@restaurants = Restaurant.all
	end

	def show
		@reviews = @restaurant.reviews
		@review = Review.new
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurants_params)
			if @restaurant.save
			redirect_to restaurant_path(@restaurant)
		else
			render "new"
		end
	end

	def edit
	end

	def update
		@restaurant.update(restaurants_params)

		redirect_to restaurant_path(@restaurant)
	end

	def destroy
		@restaurant.destroy

		redirect_to restaurants_path
	end

	private

	def fetch_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

	def restaurants_params
		params.require(:restaurant).permit(:name, :address, :phone_number, :category)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_restaurant

  def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.restaurant = @restaurant
			if @review.save
			redirect_to restaurant_path(@restaurant)
		else
			render "new"
		end
	end

	def destroy
	end

	private

	def review_params
		params.require(:review).permit(:rating, :content, :restaurant_id)
	end

	def find_restaurant
		@restaurant = Restaurant.find(params[:restaurant_id])
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
	<%= f.error_notification %>

	<% if @restaurant.errors.any? %>
		<h4> Please fill the form properly </h4>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li> <%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class= "form-inputs">
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :phone_number %>
		<%= f.input :category %>
	</div>

	<div class="form-actions">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/restaurants/index.html.erb
<h1> List of restaurants </h1>
<%= link_to 'Create a new restaurant', new_restaurant_path, class: "btn btn-primary" %>

<ul>
	<% @restaurants.each do |restaurant| %>
		<li>
			<%= link_to restaurant.name, restaurant_path(restaurant)%>
		</li>
	<% end %>
</ul>

app/views/restaurants/new.html.erb
<h3> Add a new restaurant </h3>

<%= render'form', restaurant: @restaurant %>
<%= link_to 'Return', restaurants_path %>

app/views/restaurants/show.html.erb
<h1> Restaurant </h1>
<h3> <%= @restaurant.name %></h3>
<p> <%= @restaurant.address %></p>
<p> <%= @restaurant.phone_number %></p>
<p> <%= @restaurant.category %></p>

<ul>
	<% @reviews.each do |review| %>
		<li>
			<%= review.rating %>
			<%= review.content %>
		</li>
	<% end %>
</ul>

<%= link_to 'Return', restaurants_path %>

<%= simple_form_for [ @restaurant, @review ] do |f| %>
	<%= f.error_notification %>

	<% if @restaurant.errors.any? %>
		<h4> Please fill the form properly </h4>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li> <%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<div class= "form-inputs">
		<%= f.input :rating %>
		<%= f.input :content %>
	</div>

	<div class="form-actions">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/reviews/new.html.erb
<h2> New review </h2>

<%= simple_form_for [@restaurant, @review] do |f| %>
	<%= f.input :rating %>
	<%= f.input :content%>
	<%= f.association :restaurant %>
	<%= f.submit %>
<% end %>